// import 'dart:io';
// import 'dart:typed_data';
// import 'package:flutter/material.dart';
// import 'package:get/get.dart';
// import 'package:file_picker/file_picker.dart';
// import '../Databases/util.dart';
// import '../Models/leave_model.dart';
// import '../ViewModels/leave_view_model.dart';
//
//
// class LeaveFormScreen extends StatefulWidget {
//   @override
//   State<LeaveFormScreen> createState() => _LeaveFormScreenState();
// }
//
// class _LeaveFormScreenState extends State<LeaveFormScreen> {
//   final leaveVM = Get.put(LeaveViewModel());
//   final TextEditingController reasonController = TextEditingController();
//   DateTime? startDate;
//   DateTime? endDate;
//   String leaveType = "Annual Leave";
//   bool isFullDay = true;
//   bool isHalfDay = false;
//   Uint8List? attachmentData;
//   String? attachmentFileName;
//
//   bool _isPickingFile = false; // File picker lock
//
//   int get totalDays {
//     if (startDate == null || endDate == null) return 0;
//     return endDate!.difference(startDate!).inDays + 1;
//   }
//
//   bool get isHalfDayDisabled {
//     return totalDays >= 2;
//   }
//
//   pickAttachment() async {
//     if (_isPickingFile) {
//       print('⚠️ File picker is already active');
//       return;
//     }
//
//     setState(() {
//       _isPickingFile = true;
//     });
//
//     try {
//       final result = await FilePicker.platform.pickFiles(
//         type: FileType.image,
//         allowMultiple: false,
//       );
//
//       if (result != null && result.files.isNotEmpty) {
//         final file = result.files.first;
//         try {
//           if (file.path != null) {
//             final fileBytes = await File(file.path!).readAsBytes();
//
//             // Check file size (limit to 2MB)
//             if (fileBytes.length > 5 * 1024 * 1024) {
//               Get.snackbar(
//                 "غلطی",
//                 "تصویر کا سائز 2MB سے زیادہ نہیں ہونا چاہیے",
//                 backgroundColor: Colors.red,
//                 colorText: Colors.white,
//               );
//               return;
//             }
//
//             setState(() {
//               attachmentData = fileBytes;
//               attachmentFileName = file.name;
//             });
//
//             Get.snackbar(
//               "کامیابی",
//               "تصویر کامیابی سے شامل ہوگئی",
//               backgroundColor: Colors.green,
//               colorText: Colors.white,
//               duration: Duration(seconds: 2),
//             );
//           }
//         } catch (e) {
//           Get.snackbar(
//             "غلطی",
//             "تصویر لوڈ کرنے میں خرابی: $e",
//             backgroundColor: Colors.red,
//             colorText: Colors.white,
//           );
//         }
//       }
//     } catch (e) {
//       print('🚨 File picker error: $e');
//       Get.snackbar(
//         "غلطی",
//         "فائل منتخب کرنے میں خرابی",
//         backgroundColor: Colors.red,
//         colorText: Colors.white,
//       );
//     } finally {
//       setState(() {
//         _isPickingFile = false;
//       });
//     }
//   }
//
//   submitForm() async {
//     // Validate dates
//     if (startDate == null || endDate == null) {
//       Get.snackbar("Error", "Please select dates \n براہ کرم تاریخیں منتخب کریں",
//           backgroundColor: Colors.orange, colorText: Colors.white);
//       return;
//     }
//
//     // Validate reason
//     if (reasonController.text.trim().isEmpty) {
//       Get.snackbar("Error", "Please add a Reason \n براہ کرم وجہ درج کریں",
//           backgroundColor: Colors.orange, colorText: Colors.white);
//       return;
//     }
//
//     // Validate half day
//     if (isHalfDay && totalDays > 1) {
//       Get.snackbar(
//         "غلطی",
//         "آدھے دن کی چھٹی صرف ایک دن کے لیے ہو سکتی ہے",
//         backgroundColor: Colors.orange,
//         colorText: Colors.white,
//       );
//       return;
//     }
//
//     // Format dates properly
//     String formatDateForServer(DateTime date) {
//       return "${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}";
//     }
//
//     final model = LeaveModel(
//       id: DateTime.now().millisecondsSinceEpoch.toString(),
//       leaveId: null, // Will be generated by database
//       bookerId: user_id,
//       bookerName: userName,
//       leaveType: leaveType,
//       startDate: formatDateForServer(startDate!),
//       endDate: formatDateForServer(endDate!),
//       totalDays: totalDays,
//       isHalfDay: isHalfDay,
//       reason: reasonController.text,
//       attachmentData: attachmentData, // BLOB data
//       status: 'pending',
//     );
//
//     print('📡 Submitting leave with data:');
//     print('   Booker ID: ${model.bookerId}');
//     print('   Booker Name: ${model.bookerName}');
//     print('   Leave Type: ${model.leaveType}');
//     print('   Start Date: ${model.startDate}');
//     print('   End Date: ${model.endDate}');
//     print('   Total Days: ${model.totalDays}');
//     print('   Is Half Day: ${model.isHalfDay}');
//     print('   Reason: ${model.reason}');
//     print('   Attachment: ${model.attachmentData != null ? "Present (${model.attachmentData!.length} bytes)" : "Not Present"}');
//     print('   JSON: ${model.toJson()}');
//
//     final success = await leaveVM.submitLeave(model);
//
//     if (success) {
//       Get.snackbar(
//         "کامیابی",
//         "چھٹی کی درخواست کامیابی سے جمع ہوگئی",
//         backgroundColor: Colors.green,
//         colorText: Colors.white,
//         duration: Duration(seconds: 3),
//       );
//       resetForm();
//     } else {
//       Get.snackbar(
//         "غلطی",
//         "چھٹی جمع کرانے میں ناکامی",
//         backgroundColor: Colors.red,
//         colorText: Colors.white,
//       );
//     }
//   }
//
//   void resetForm() {
//     setState(() {
//       reasonController.clear();
//       startDate = null;
//       endDate = null;
//       leaveType = "Annual Leave";
//       isFullDay = true;
//       isHalfDay = false;
//       attachmentData = null;
//       attachmentFileName = null;
//     });
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: Color(0xFFF5F7FA),
//       appBar: AppBar(
//         title: const Text(
//           "چھٹی کی درخواست",
//           style: TextStyle(
//             color: Colors.white,
//             fontSize: 20,
//             fontWeight: FontWeight.w600,
//           ),
//         ),
//         centerTitle: true,
//         backgroundColor: Colors.blueGrey,
//         elevation: 0,
//         iconTheme: IconThemeData(color: Colors.white),
//       ),
//       body: SingleChildScrollView(
//         padding: EdgeInsets.symmetric(horizontal: 16, vertical: 24),
//         child: Center(
//           child: Container(
//             constraints: BoxConstraints(maxWidth: 900),
//             padding: EdgeInsets.all(24),
//             decoration: BoxDecoration(
//               color: Colors.white,
//               borderRadius: BorderRadius.circular(16),
//               boxShadow: [
//                 BoxShadow(
//                   color: Colors.black.withOpacity(0.08),
//                   blurRadius: 20,
//                   offset: Offset(0, 4),
//                 )
//               ],
//             ),
//             child: Column(
//               crossAxisAlignment: CrossAxisAlignment.start,
//               children: formWidgets(),
//             ),
//           ),
//         ),
//       ),
//     );
//   }
//
//   List<Widget> formWidgets() {
//     return [
//       sectionTitle("Applicant Details", "درخواست گزار کی معلومات"),
//       SizedBox(height: 20),
//
//       LayoutBuilder(
//         builder: (context, constraints) {
//           return constraints.maxWidth < 600
//               ? Column(
//             children: [
//               readOnlyField("Booker ID", "بکر آئی ڈی", user_id),
//               SizedBox(height: 16),
//               readOnlyField("Booker Name", "بکر نام", userName),
//             ],
//           )
//               : Row(
//             children: [
//               Expanded(
//                 child: readOnlyField("Booker ID", "بکر آئی ڈی", user_id),
//               ),
//               SizedBox(width: 16),
//               Expanded(
//                 child: readOnlyField("Booker Name", "بکر نام", userName),
//               ),
//             ],
//           );
//         },
//       ),
//
//       SizedBox(height: 32),
//       Divider(height: 1, color: Colors.grey.shade300),
//       SizedBox(height: 32),
//
//       sectionTitle("Leave Information", "چھٹی کی معلومات"),
//       SizedBox(height: 20),
//
//       dropdownField(),
//       SizedBox(height: 16),
//
//       LayoutBuilder(
//         builder: (context, constraints) {
//           return constraints.maxWidth < 600
//               ? Column(
//             children: [
//               datePicker(
//                 "Start Date",
//                 "شروع کی تاریخ",
//                     (d) => setState(() => startDate = d),
//                 startDate,
//               ),
//               SizedBox(height: 16),
//               datePicker(
//                 "End Date",
//                 "اختتام کی تاریخ",
//                     (d) => setState(() => endDate = d),
//                 endDate,
//               ),
//             ],
//           )
//               : Row(
//             children: [
//               Expanded(
//                 child: datePicker(
//                   "Start Date",
//                   "شروع کی تاریخ",
//                       (d) => setState(() => startDate = d),
//                   startDate,
//                 ),
//               ),
//               SizedBox(width: 16),
//               Expanded(
//                 child: datePicker(
//                   "End Date",
//                   "اختتام کی تاریخ",
//                       (d) => setState(() => endDate = d),
//                   endDate,
//                 ),
//               ),
//             ],
//           );
//         },
//       ),
//
//       SizedBox(height: 16),
//       infoField("Total Days", "کل دن", totalDays.toString()),
//       SizedBox(height: 20),
//
//       Text(
//         "Leave Duration / چھٹی کی مدت",
//         style: TextStyle(
//           fontSize: 15,
//           fontWeight: FontWeight.w600,
//           color: Colors.grey.shade700,
//         ),
//       ),
//       SizedBox(height: 12),
//
//       Wrap(
//         spacing: 24,
//         runSpacing: 12,
//         children: [
//           InkWell(
//             onTap: () {
//               setState(() {
//                 isFullDay = true;
//                 isHalfDay = false;
//               });
//             },
//             child: Row(
//               mainAxisSize: MainAxisSize.min,
//               children: [
//                 Container(
//                   width: 20,
//                   height: 20,
//                   decoration: BoxDecoration(
//                     shape: BoxShape.circle,
//                     border: Border.all(
//                       color: isFullDay ? Color(0xFF1976D2) : Colors.grey.shade400,
//                       width: 2,
//                     ),
//                   ),
//                   child: isFullDay
//                       ? Center(
//                     child: Container(
//                       width: 12,
//                       height: 12,
//                       decoration: BoxDecoration(
//                         shape: BoxShape.circle,
//                         color: Color(0xFF1976D2),
//                       ),
//                     ),
//                   )
//                       : null,
//                 ),
//                 SizedBox(width: 8),
//                 Text(
//                   "Full Day / پورا دن",
//                   style: TextStyle(
//                     fontSize: 15,
//                     color: Colors.grey.shade800,
//                   ),
//                 ),
//               ],
//             ),
//           ),
//           InkWell(
//             onTap: isHalfDayDisabled
//                 ? null
//                 : () {
//               setState(() {
//                 isHalfDay = true;
//                 isFullDay = false;
//               });
//             },
//             child: Row(
//               mainAxisSize: MainAxisSize.min,
//               children: [
//                 Container(
//                   width: 20,
//                   height: 20,
//                   decoration: BoxDecoration(
//                     shape: BoxShape.circle,
//                     border: Border.all(
//                       color: isHalfDay && !isHalfDayDisabled
//                           ? Color(0xFF1976D2)
//                           : Colors.grey.shade400,
//                       width: 2,
//                     ),
//                     color: isHalfDayDisabled
//                         ? Colors.grey.shade200
//                         : Colors.transparent,
//                   ),
//                   child: isHalfDay && !isHalfDayDisabled
//                       ? Center(
//                     child: Container(
//                       width: 12,
//                       height: 12,
//                       decoration: BoxDecoration(
//                         shape: BoxShape.circle,
//                         color: Color(0xFF1976D2),
//                       ),
//                     ),
//                   )
//                       : null,
//                 ),
//                 SizedBox(width: 8),
//                 Text(
//                   "Half Day / آدھا دن",
//                   style: TextStyle(
//                     fontSize: 15,
//                     color: isHalfDayDisabled
//                         ? Colors.grey.shade500
//                         : Colors.grey.shade800,
//                   ),
//                 ),
//                 if (isHalfDayDisabled) SizedBox(width: 4),
//                 if (isHalfDayDisabled)
//                   Text(
//                     "(غیر فعال)",
//                     style: TextStyle(
//                       fontSize: 12,
//                       color: Colors.blueGrey.shade700,
//                       fontStyle: FontStyle.italic,
//                     ),
//                   ),
//               ],
//             ),
//           ),
//         ],
//       ),
//
//       if (isHalfDayDisabled) ...[
//         SizedBox(height: 8),
//         Padding(
//           padding: const EdgeInsets.only(left: 8.0),
//           child: Text(
//             "نوٹ: آدھے دن کی چھٹی صرف ایک دن کے لیے منتخب کی جا سکتی ہے۔",
//             style: TextStyle(
//               fontSize: 12,
//               color: Colors.blueGrey.shade700,
//               fontStyle: FontStyle.italic,
//             ),
//           ),
//         ),
//       ],
//
//       SizedBox(height: 24),
//       textArea("Reason for Leave", "چھٹی کی وجہ", reasonController),
//       SizedBox(height: 20),
//       attachmentButton(),
//       SizedBox(height: 32),
//
//       Obx(() => leaveVM.isLoading.value
//           ? Center(
//         child: CircularProgressIndicator(
//           valueColor: AlwaysStoppedAnimation<Color>(Colors.blueGrey),
//         ),
//       )
//           : SizedBox(
//         width: double.infinity,
//         height: 52,
//         child: ElevatedButton(
//           style: ElevatedButton.styleFrom(
//             backgroundColor: Colors.blueGrey,
//             foregroundColor: Colors.white,
//             elevation: 0,
//             shape: RoundedRectangleBorder(
//               borderRadius: BorderRadius.circular(12),
//             ),
//           ),
//           onPressed: submitForm,
//           child: Text(
//             "Submit Application / درخواست جمع کریں",
//             style: TextStyle(
//               fontSize: 16,
//               fontWeight: FontWeight.w600,
//               letterSpacing: 0.5,
//             ),
//           ),
//         ),
//       )),
//     ];
//   }
//
//   Widget sectionTitle(String english, String urdu) {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           english,
//           style: TextStyle(
//             fontSize: 18,
//             fontWeight: FontWeight.bold,
//             color: Colors.blueGrey,
//             letterSpacing: 0.3,
//           ),
//         ),
//         SizedBox(height: 4),
//         Text(
//           urdu,
//           style: TextStyle(
//             fontSize: 16,
//             fontWeight: FontWeight.w500,
//             color: Colors.grey.shade600,
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget readOnlyField(String labelEn, String labelAr, String value) {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "$labelEn / $labelAr",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         Container(
//           width: double.infinity,
//           padding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
//           decoration: BoxDecoration(
//             color: Colors.grey.shade50,
//             borderRadius: BorderRadius.circular(10),
//             border: Border.all(color: Colors.grey.shade300),
//           ),
//           child: Text(
//             value,
//             style: TextStyle(
//               fontSize: 15,
//               color: Colors.grey.shade800,
//             ),
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget infoField(String labelEn, String labelAr, String value) {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "$labelEn / $labelAr",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         Container(
//           width: double.infinity,
//           padding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
//           decoration: BoxDecoration(
//             color: Colors.blueGrey.shade50,
//             borderRadius: BorderRadius.circular(10),
//             border: Border.all(color: Colors.blueGrey.withOpacity(0.3)),
//           ),
//           child: Text(
//             value.isEmpty ? "0" : value,
//             style: TextStyle(
//               fontSize: 15,
//               fontWeight: FontWeight.w600,
//               color: Colors.blueGrey,
//             ),
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget dropdownField() {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "Leave Type / چھٹی کی قسم",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         Container(
//           decoration: BoxDecoration(
//             color: Colors.white,
//             borderRadius: BorderRadius.circular(10),
//             border: Border.all(color: Colors.grey.shade300),
//           ),
//           child: DropdownButtonFormField(
//             decoration: InputDecoration(
//               contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
//               border: InputBorder.none,
//             ),
//             value: leaveType,
//             items: [
//               DropdownMenuItem(
//                 value: "Annual Leave",
//                 child: Text("Annual Leave / سالانہ چھٹی"),
//               ),
//               DropdownMenuItem(
//                 value: "Sick Leave",
//                 child: Text("Sick Leave / بیماری کی چھٹی"),
//               ),
//               DropdownMenuItem(
//                 value: "Urgent Leave",
//                 child: Text("Urgent Leave / ضروری چھٹی "),
//               ),
//               DropdownMenuItem(
//                 value: "Short Leave",
//                 child: Text("Short Leave / مختصر چھٹی"),
//               ),
//             ],
//             onChanged: (v) => setState(() => leaveType = v!),
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget datePicker(
//       String labelEn, String labelAr, Function(DateTime) onPick, DateTime? date) {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "$labelEn / $labelAr",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         InkWell(
//           onTap: () async {
//             final d = await showDatePicker(
//               context: context,
//               firstDate: DateTime(2020),
//               lastDate: DateTime(2030),
//               initialDate: date ?? DateTime.now(),
//               builder: (context, child) {
//                 return Theme(
//                   data: Theme.of(context).copyWith(
//                     colorScheme: ColorScheme.light(
//                       primary: Color(0xFF1976D2),
//                     ),
//                   ),
//                   child: child!,
//                 );
//               },
//             );
//             if (d != null) onPick(d);
//           },
//           child: Container(
//             width: double.infinity,
//             padding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
//             decoration: BoxDecoration(
//               color: Colors.white,
//               borderRadius: BorderRadius.circular(10),
//               border: Border.all(color: Colors.grey.shade300),
//             ),
//             child: Row(
//               mainAxisAlignment: MainAxisAlignment.spaceBetween,
//               children: [
//                 Text(
//                   date != null
//                       ? "${date.day.toString().padLeft(2, '0')}-${date.month.toString().padLeft(2, '0')}-${date.year}"
//                       : "Select date",
//                   style: TextStyle(
//                     fontSize: 15,
//                     color: date != null ? Colors.grey.shade800 : Colors.grey.shade500,
//                   ),
//                 ),
//                 Icon(Icons.calendar_today, size: 20, color: Color(0xFF1976D2)),
//               ],
//             ),
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget textArea(String labelEn, String labelAr, TextEditingController controller) {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "$labelEn / $labelAr",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         TextField(
//           controller: controller,
//           maxLines: 4,
//           decoration: InputDecoration(
//             hintText: "Enter reason for leave...",
//             hintStyle: TextStyle(color: Colors.grey.shade400),
//             filled: true,
//             fillColor: Colors.white,
//             contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
//             border: OutlineInputBorder(
//               borderRadius: BorderRadius.circular(10),
//               borderSide: BorderSide(color: Colors.grey.shade300),
//             ),
//             enabledBorder: OutlineInputBorder(
//               borderRadius: BorderRadius.circular(10),
//               borderSide: BorderSide(color: Colors.grey.shade300),
//             ),
//             focusedBorder: OutlineInputBorder(
//               borderRadius: BorderRadius.circular(10),
//               borderSide: BorderSide(color: Color(0xFF1976D2), width: 2),
//             ),
//           ),
//         ),
//       ],
//     );
//   }
//
//   Widget attachmentButton() {
//     return Column(
//       crossAxisAlignment: CrossAxisAlignment.start,
//       children: [
//         Text(
//           "Attachment / اٹیچمنٹ",
//           style: TextStyle(
//             fontSize: 14,
//             fontWeight: FontWeight.w600,
//             color: Colors.grey.shade700,
//           ),
//         ),
//         SizedBox(height: 8),
//         Row(
//           children: [
//             Expanded(
//               child: InkWell(
//                 onTap: _isPickingFile ? null : pickAttachment,
//                 child: Container(
//                   padding: EdgeInsets.symmetric(vertical: 14, horizontal: 16),
//                   decoration: BoxDecoration(
//                     color: attachmentData != null
//                         ? Colors.green.shade50
//                         : Colors.blueGrey.shade50,
//                     borderRadius: BorderRadius.circular(10),
//                     border: Border.all(
//                       color: attachmentData != null
//                           ? Colors.green.shade300
//                           : Colors.blueGrey.withOpacity(0.3),
//                     ),
//                   ),
//                   child: Row(
//                     children: [
//                       _isPickingFile
//                           ? SizedBox(
//                         width: 22,
//                         height: 22,
//                         child: CircularProgressIndicator(
//                           strokeWidth: 2,
//                           valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF1976D2)),
//                         ),
//                       )
//                           : Icon(
//                         attachmentData != null
//                             ? Icons.check_circle
//                             : Icons.attach_file,
//                         color: attachmentData != null
//                             ? Colors.green.shade700
//                             : Color(0xFF1976D2),
//                         size: 22,
//                       ),
//                       SizedBox(width: 12),
//                       Expanded(
//                         child: Column(
//                           crossAxisAlignment: CrossAxisAlignment.start,
//                           children: [
//                             Text(
//                               _isPickingFile
//                                   ? "Loading..."
//                                   : attachmentData == null
//                                   ? "Add Image (Optional) / تصویر شامل کریں"
//                                   : "Image Added / تصویر شامل ہو گئی",
//                               style: TextStyle(
//                                 fontSize: 15,
//                                 color: attachmentData != null
//                                     ? Colors.green.shade700
//                                     : Colors.blueGrey,
//                                 fontWeight: FontWeight.w500,
//                               ),
//                             ),
//                             if (attachmentFileName != null) ...[
//                               SizedBox(height: 4),
//                               Text(
//                                 attachmentFileName!,
//                                 style: TextStyle(
//                                   fontSize: 12,
//                                   color: Colors.grey.shade600,
//                                 ),
//                                 overflow: TextOverflow.ellipsis,
//                               ),
//                             ],
//                           ],
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//             ),
//             if (attachmentData != null && !_isPickingFile) ...[
//               SizedBox(width: 12),
//               InkWell(
//                 onTap: () {
//                   showDialog(
//                     context: context,
//                     builder: (context) => Dialog(
//                       child: Container(
//                         width: 300,
//                         height: 400,
//                         child: Image.memory(
//                           attachmentData!,
//                           fit: BoxFit.contain,
//                         ),
//                       ),
//                     ),
//                   );
//                 },
//                 child: Container(
//                   padding: EdgeInsets.all(8),
//                   decoration: BoxDecoration(
//                     color: Colors.blueGrey.shade50,
//                     borderRadius: BorderRadius.circular(8),
//                     border: Border.all(color: Colors.blueGrey.shade300),
//                   ),
//                   child: Icon(
//                     Icons.preview,
//                     color: Colors.blueGrey.shade700,
//                     size: 24,
//                   ),
//                 ),
//               ),
//             ],
//           ],
//         ),
//         if (attachmentData != null) ...[
//           SizedBox(height: 8),
//           Padding(
//             padding: const EdgeInsets.only(left: 8.0),
//             child: Text(
//               "تصویر کا سائز: ${(attachmentData!.length / 1024).toStringAsFixed(2)} KB",
//               style: TextStyle(
//                 fontSize: 12,
//                 color: Colors.grey.shade600,
//                 fontStyle: FontStyle.italic,
//               ),
//             ),
//           ),
//         ],
//       ],
//     );
//   }
// }